# filepath: 
FROM public.ecr.aws/lambda/python:3.12

WORKDIR /workspace

# Copy build.sh into a directory that won't be overwritten
COPY build.sh /opt/build.sh
RUN chmod +x /opt/build.sh

# Run the build script by default
ENTRYPOINT ["/bin/bash", "-lc", "/opt/build.sh"]